list: $/eev/company/models/social/columns.yaml
modelClass: EEV\Company\Models\Social
title: 'eev.company::lang.social_networks'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eev/company/socialcontroller/update/:id'
