name: 'eev.company::lang.address'
modelClass: EEV\Company\Models\Address
form: $/eev/company/models/address/fields.yaml
defaultRedirect: eev/company/addresscontroller
create:
    title: 'eev.company::lang.creating'
    redirect: 'eev/company/addresscontroller/update/:id'
    redirectClose: eev/company/addresscontroller
    flashSave: 'eev.company::lang.saved'
update:
    title: 'eev.company::lang.editing'
    redirect: eev/company/addresscontroller
    redirectClose: eev/company/addresscontroller
    flashSave: 'eev.company::lang.saved'
preview: {  }
