title: 'eev.company::lang.addresses'
modelClass: EEV\Company\Models\Address
list: $/eev/company/models/address/columns.yaml
recordUrl: 'eev/company/addresscontroller/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
